hardware_interface:
  - name: "baxter_hardware"
    type: "baxter_bridge_hardware/BaxterHardwareInterface"
    parameters:
      robot_ip: "192.168.42.2"
      joint_names:
        - head_pan
        - left_s0
        - left_s1
        - left_e0
        - left_e1
        - left_w0
        - left_w1
        - left_w2
        - right_s0
        - right_s1
        - right_e0
        - right_e1
        - right_w0
        - right_w1
        - right_w2
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity