controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Hardware interface for Baxter robot
    baxter_hardware:
      type: mock_components/GenericSystem
      hardware_interface_type: SystemInterface

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Left Arm Controller
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Right Arm Controller  
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - head_pan
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2

# Left Arm Controller Configuration
left_arm_controller:
  ros__parameters:
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      left_s0: {trajectory: 0.1, goal: 0.1}
      left_s1: {trajectory: 0.1, goal: 0.1}
      left_e0: {trajectory: 0.1, goal: 0.1}
      left_e1: {trajectory: 0.1, goal: 0.1}
      left_w0: {trajectory: 0.1, goal: 0.1}
      left_w1: {trajectory: 0.1, goal: 0.1}
      left_w2: {trajectory: 0.1, goal: 0.1}

# Right Arm Controller Configuration
right_arm_controller:
  ros__parameters:
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      right_s0: {trajectory: 0.1, goal: 0.1}
      right_s1: {trajectory: 0.1, goal: 0.1}
      right_e0: {trajectory: 0.1, goal: 0.1}
      right_e1: {trajectory: 0.1, goal: 0.1}
      right_w0: {trajectory: 0.1, goal: 0.1}
      right_w1: {trajectory: 0.1, goal: 0.1}
      right_w2: {trajectory: 0.1, goal: 0.1}