#!/bin/bash

echo "=== Baxter ROS1-ROS2 Bridge Commands ==="
echo ""
echo "START/STOP:"
echo "  ./start_baxter_bridge.sh     # Start all containers"
echo "  ./stop_baxter_bridge.sh      # Stop all containers"
echo ""
echo "ACCESS CONTAINERS:"
echo "  docker exec -it baxter_ros1_container bash"
echo "  docker exec -it moveit_ros2_container bash"
echo ""
echo "VIEW BRIDGE LOGS:"
echo "  docker logs -f ros_bridge_container"
echo ""
echo "BAXTER ROS1 COMMANDS:"
echo "  rostopic list                # List all topics"
echo "  rosrun baxter_tools enable_robot.py -e    # Enable robot"
echo "  rosrun baxter_tools enable_robot.py -d    # Disable robot"
echo "  rosrun baxter_interface joint_trajectory_action_server.py  # Start trajectory server"
echo ""
echo "ROS2 COMMANDS:"
echo "  ros2 topic list              # List ROS2 topics"
echo "  ros2 run moveit_setup_assistant moveit_setup_assistant  # Setup MoveIt"
echo ""
echo "LAUNCH MOVEIT2:"
echo "  ./launch_moveit2_baxter.sh   # Launch MoveIt Setup Assistant"

