/**:
  ros__parameters:
    joint_limits:
      left_s0:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      left_s1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      left_e0:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      left_e1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      left_w0:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      left_w1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      left_w2:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_s0:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_s1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_e0:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_e1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_w0:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_w1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      right_w2:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
        max_jerk: 0.0
      head_pan:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 3.0
        has_jerk_limits: false
        max_jerk: 0.0