/**:
  ros__parameters:
    planner_configs:
      SBLkConfigDefault:
        type: geometric::SBL
        range: 0.0
      ESTkConfigDefault:
        type: geometric::EST
        range: 0.0
        goal_bias: 0.05
      LBKPIECEkConfigDefault:
        type: geometric::LBKPIECE
        range: 0.0
        border_fraction: 0.9
        min_valid_path_fraction: 0.5
      BKPIECEkConfigDefault:
        type: geometric::BKPIECE
        range: 0.0
        border_fraction: 0.9
        failed_expansion_score_factor: 0.5
        min_valid_path_fraction: 0.5
      KPIECEkConfigDefault:
        type: geometric::KPIECE
        range: 0.0
        goal_bias: 0.05
        border_fraction: 0.9
        failed_expansion_score_factor: 0.5
        min_valid_path_fraction: 0.5
      RRTkConfigDefault:
        type: geometric::RRT
        range: 0.0
        goal_bias: 0.05
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
      RRTstarkConfigDefault:
        type: geometric::RRTstar
        range: 0.0
        goal_bias: 0.05
        delay_collision_checking: 1
      TRRTkConfigDefault:
        type: geometric::TRRT
        range: 0.0
        goal_bias: 0.05
        max_states_failed: 10
        temp_change_factor: 2.0
        min_temperature: 10e-10
        init_temperature: 10e-6
        frountier_threshold: 0.0
        frountierNodeRatio: 0.1
        k_constant: 0.0
      PRMkConfigDefault:
        type: geometric::PRM
        max_nearest_neighbors: 10
      PRMstarkConfigDefault:
        type: geometric::PRMstar

    left_arm:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - SBLkConfigDefault
        - ESTkConfigDefault
        - LBKPIECEkConfigDefault
        - BKPIECEkConfigDefault
        - KPIECEkConfigDefault
        - RRTkConfigDefault
        - RRTConnectkConfigDefault
        - RRTstarkConfigDefault
        - TRRTkConfigDefault
        - PRMkConfigDefault
        - PRMstarkConfigDefault
      projection_evaluator: joints(left_s0,left_s1)
      longest_valid_segment_fraction: 0.01

    right_arm:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - SBLkConfigDefault
        - ESTkConfigDefault
        - LBKPIECEkConfigDefault
        - BKPIECEkConfigDefault
        - KPIECEkConfigDefault
        - RRTkConfigDefault
        - RRTConnectkConfigDefault
        - RRTstarkConfigDefault
        - TRRTkConfigDefault
        - PRMkConfigDefault
        - PRMstarkConfigDefault
      projection_evaluator: joints(right_s0,right_s1)
      longest_valid_segment_fraction: 0.01

    both_arms:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - SBLkConfigDefault
        - ESTkConfigDefault
        - LBKPIECEkConfigDefault
        - BKPIECEkConfigDefault
        - KPIECEkConfigDefault
        - RRTkConfigDefault
        - RRTConnectkConfigDefault
        - RRTstarkConfigDefault
        - TRRTkConfigDefault
        - PRMkConfigDefault
        - PRMstarkConfigDefault
      projection_evaluator: joints(left_s0,left_s1,right_s0,right_s1)
      longest_valid_segment_fraction: 0.01